CREATE DATABASE CTEST USING CODESET UTF-8 TERRITORY US COLLATE USING SYSTEM PAGESIZE 32768
UPDATE DATABASE CONFIGURATION FOR CTEST USING LOGFILSIZ 20000
UPDATE DB CONFIG FOR CTEST USING AUTO_MAINT ON AUTO_TBL_MAINT ON AUTO_RUNSTATS ON
connect to CTEST 
GRANT CREATE_EXTERNAL_ROUTINE ON DATABASE TO USER DB2ADMIN
GRANT LOAD ON DATABASE TO USER DB2ADMIN
CREATE TABLESPACE SYSTOOLSPACE IN IBMCATGROUP MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 4
CALL SYSPROC.ADMIN_TASK_ADD ( 'DUMMY',  NULL,    NULL,    NULL,   NULL, 'SYSPROC', 'ADMIN_CMD',  'VALUES(''DUMMY'')',   NULL,    NULL ) -- so that admintaskstatus is available
CALL SYSPROC.ADMIN_TASK_REMOVE ( 'DUMMY' , NULL )
GRANT  UPDATE ON TABLE SYSTOOLS.ADMINTASKSTATUS TO USER DB2ADMIN
alter bufferpool IBMDEFAULTBP IMMEDIATE SIZE 15000 AUTOMATIC