FROM java:8

COPY target/carbon-platform.jar /opt/carbon/carbon-platform.jar
COPY target/lib /opt/carbon/lib

EXPOSE 8083
EXPOSE 5005

ENTRYPOINT java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar /opt/carbon/carbon-platform.jar