# Header
nav:
- name: Get Started 
  path: /get-started
  children: null
- name: Documentation
  path: /documentation
  children:
	- name: Quick Start Guide
	  path: /quick-start-guide
	  children: null
	- name: Essential Concepts
	  path: /essential-concepts
	  children: null
	- name: JavaScript SDK
	  path: /javascript-sdk
	  children:
	    - name: Guide
	      path: /getting-started
	      children: null
	    - name: API Reference
	      url: https://carbonldp.github.io/carbonldp-js-sdk/
	      children: null
	- name: REST API
	  path: /rest-api
	  children: null
- name: Community & Support
  path: /community-and-support
  children: null
- name: Blog
  path: /blog
  children: null
- name: About 
  path: /about
  children: null
rss: /atom.xml

#Versions
versions:
   current: v0.x.x
   allVersions:
    - v0.x.x
    - v1.0.x


#Excerpt Link
excerpt_link: Read More